# This file configures the analyzer for Dart and Flutter
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    annotate_overrides: true
    avoid_empty_else: true
    curly_braces_in_flow_control_structures: true

analyzer:
  errors:
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
