// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Firebase configuration from google-services.json
  // Project: elder-care-995b8

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQGeCD5HnoQVEANvKZ0PNAYA6-IttsJUg',
    appId: '1:163430176460:web:e75dafa4ef7488c5a85469',
    messagingSenderId: '163430176460',
    projectId: 'elder-care-995b8',
    authDomain: 'elder-care-995b8.firebaseapp.com',
    storageBucket: 'elder-care-995b8.firebasestorage.app',
    databaseURL: 'https://elder-care-995b8-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQGeCD5HnoQVEANvKZ0PNAYA6-IttsJUg',
    appId: '1:163430176460:android:e75dafa4ef7488c5a85469',
    messagingSenderId: '163430176460',
    projectId: 'elder-care-995b8',
    storageBucket: 'elder-care-995b8.firebasestorage.app',
    databaseURL: 'https://elder-care-995b8-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQGeCD5HnoQVEANvKZ0PNAYA6-IttsJUg',
    appId: '1:163430176460:ios:e75dafa4ef7488c5a85469',
    messagingSenderId: '163430176460',
    projectId: 'elder-care-995b8',
    storageBucket: 'elder-care-995b8.firebasestorage.app',
    databaseURL: 'https://elder-care-995b8-default-rtdb.firebaseio.com',
    iosBundleId: 'com.elder.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQGeCD5HnoQVEANvKZ0PNAYA6-IttsJUg',
    appId: '1:163430176460:macos:e75dafa4ef7488c5a85469',
    messagingSenderId: '163430176460',
    projectId: 'elder-care-995b8',
    storageBucket: 'elder-care-995b8.firebasestorage.app',
    databaseURL: 'https://elder-care-995b8-default-rtdb.firebaseio.com',
    iosBundleId: 'com.elder.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQGeCD5HnoQVEANvKZ0PNAYA6-IttsJUg',
    appId: '1:163430176460:web:e75dafa4ef7488c5a85469',
    messagingSenderId: '163430176460',
    projectId: 'elder-care-995b8',
    authDomain: 'elder-care-995b8.firebaseapp.com',
    storageBucket: 'elder-care-995b8.firebasestorage.app',
    databaseURL: 'https://elder-care-995b8-default-rtdb.firebaseio.com',
  );
}
